import json
import os

def update_translations(lang, updates):
    file_path = os.path.join(r"d:\Full-Projects\threadsV2\front\public\locales", lang, "translation.json")
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    data.update(updates)
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

it_updates_1 = {
  "You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.": "Sei responsabile di mantenere la riservatezza delle credenziali del tuo account e di tutte le attività svolte con il tuo account.",
  "But every post you share today becomes a memory tomorrow. Keep broadcasting your story!": "Ma ogni post che condividi oggi diventerà un ricordo domani. Continua a trasmettere la tua storia!",
  "✏️ Highlight updated successfully.": "✏️ Highlight aggiornato con successo.",
  "✅ Highlight created successfully!": "✅ Highlight creato con successo!",
  "✅ Highlights reordered.": "✅ Highlight riordinati.",
  "✅ Order saved.": "✅ Ordine salvato.",
  "✅ Reel shared successfully.": "✅ Reel condiviso con successo.",
  "✅ Signal broadcasted successfully!": "✅ Segnale trasmesso con successo!",
  "✅ Story published successfully.": "✅ Storia pubblicata con successo.",
  "✅ Story shared successfully!": "✅ Storia condivisa con successo!",
  "❌ Broadcast failed.": "❌ Trasmissione fallita.",
  "❌ Could not update highlight.": "❌ Impossibile aggiornare l'highlight.",
  "❌ Failed to add story.": "❌ Impossibile aggiungere la storia.",
  "❌ Failed to react.": "❌ Reazione fallita.",
  "❌ Failed to reorder highlights.": "❌ Impossibile riordinare gli highlight.",
  "❌ Failed to reorder stories.": "❌ Impossibile riordinare le storie.",
  "❌ Failed to share story.": "❌ Impossibile condividere la storia.",
  "❌ Failed to share the Reel.": "❌ Impossibile condividere il Reel.",
  "❌ Failed to toggle love.": "❌ Impossibile cambiare lo stato del mi piace.",
  "⚠️ Please select a video first.": "⚠️ Seleziona prima un video.",
  "⚠️ Please upload a valid video file.": "⚠️ Carica un file video valido.",
  "About Hub": "Informazioni sull'Hub",
  "About Notification Blocking": "Blocco delle Notifiche",
  "Accept All Protocols": "Accetta Tutti i Protocolli",
  "Acceptance": "Accettazione",
  "Acceptance of Terms": "Accettazione dei Termini",
  "Access Registry": "Registro degli Accessi",
  "Account Access": "Accesso all'Account",
  "Account Exports": "Esportazioni Account",
  "Account Governance": "Governance dell'Account",
  "Account Privacy": "Privacy dell'Account",
  "Account Verified": "Account Verificato",
  "accounts": "account",
  "Active Discourse": "Discorso Attivo",
  "Active Nodes": "Nodi Attivi",
  "Active Sessions": "Sessioni Attive",
  "Active Signals": "Segnali Attivi",
  "Active Stream": "Flusso Attivo",
  "Add a new interest": "Aggiungi un nuovo interesse",
  "Add a reply...": "Aggiungi una risposta...",
  "Add numbers and special characters": "Aggiungi numeri e caratteri speciali",
  "Add Stories": "Aggiungi Storie",
  "Add tag": "Aggiungi tag",
  "Additional Details": "Dettagli Aggiuntivi",
  "Adjust your tuning or initialize a new node to start a resonance.": "Regola la tua sintonizzazione o inizializza un nuovo nodo per avviare una risonanza.",
  "All Clear!": "Tutto Chiaro!",
  "All Dimensions": "Tutte le Dimensioni",
  "All fields are required": "Tutti i campi sono obbligatori",
  "All Phases": "Tutte le Fasi",
  "All Priorities": "Tutte le Priorità",
  "All Streams": "Tutti i Flussi",
  "All Types": "Tutti i Tipi",
  "All your stories are already in this highlight": "Tutte le tue storie sono già in questo highlight",
  "Allow accounts you follow and anyone you message to see when you were last active.": "Consenti agli account che segui e a chiunque ti invii messaggi di vedere quando sei stato attivo l'ultima volta.",
  "Allow All": "Consenti Tutto",
  "Almost there...": "Ci siamo quasi...",
  "Amplify Post": "Amplifica Post",
  "Analytical": "Analitico",
  "Annual Sync": "Sincronizzazione Annuale",
  "Anyone can view": "Chiunque può visualizzare",
  "Are you sure you want to delete this story?": "Sei sicuro di voler eliminare questa storia?",
  "Atmosphere is silent... No nodes available.": "L'atmosfera è silenziosa... Nessun nodo disponibile.",
  "Avoid common words and patterns": "Evita parole e schemi comuni",
  "Back to Viewer": "Torna al Visualizzatore",
  "Be Constructive": "Sii Costruttivo",
  "Be Kind and Respectful": "Sii Gentile e Rispettoso",
  "Be the first to broadcast a video to the world!": "Sii il primo a trasmettere un video al mondo!",
  "Billing Inquiry": "Richiesta di Fatturazione",
  "Broadcast Signal": "Segnale di Trasmissione",
  "Broadcast Transmission": "Trasmissione Segnale",
  "Broadcasting System": "Sistema di Trasmissione",
  "Broadcasting...": "Trasmissione in corso...",
  "Broadcasts": "Trasmissioni",
  "Browse FAQ": "Sfoglia le FAQ",
  "Calibrating Audio...": "Calibrazione Audio...",
  "Challenges Coming Soon!": "Sfide in Arrivo!",
  "Check updates": "Controlla aggiornamenti",
  "Choose a stronger password": "Scegli una password più complessa",
  "Chronological": "Cronologico",
  "Comment Reports": "Segnalazioni Commenti",
  "Commercial Partnerships": "Partnership Commerciali",
  "Common sense prevails. No specific rules set yet.": "Prevale il buon senso. Nessuna regola specifica impostata ancora.",
  "Community Guidelines": "Linee Guida della Comunità",
  "Community Name": "Nome della Comunità",
  "Complete actions, earn XP, and unlock exclusive perks at higher tiers.": "Completa azioni, guadagna XP e sblocca vantaggi esclusivi ai livelli superiori.",
  "Complete tasks": "Completa compiti",
  "Comprehensive documentation on how your digital footprint is analyzed and protected.": "Documentazione completa su come la tua impronta digitale viene analizzata e protetta.",
  "Conduct": "Condotta",
  "Configuration": "Configurazione",
  "Configuration Active": "Configurazione Attiva",
  "Configure critical system parameters": "Configura i parametri critici di sistema",
  "Configure Settings": "Configura Impostazioni",
  "Confirm Delete": "Conferma Eliminazione",
  "Confirm Termination": "Conferma Terminazione",
  "Connect with nodes of similar resonance across the global grid.": "Connettiti con nodi di risonanza simile attraverso la griglia globale.",
  "Connect with our resonance team for technical assistance or network inquiries.": "Connettiti con il nostro team di risonanza per assistenza tecnica o richieste di rete.",
  "Connection Status": "Stato della Connessione",
  "Constructive": "Costruttivo",
  "Contact Email": "Email di Contatto",
  "Content unavailable": "Contenuto non disponibile",
  "Contribute to discourse": "Contribuisci al discorso",
  "Control visibility of your profile and activity.": "Controlla la visibilità del tuo profilo e della tua attività.",
  "Controlling how we utilize digital fingerprints to synchronize your network pulse.": "Gestisci come utilizziamo le impronte digitali per sincronizzare il tuo impulso di rete.",
  "Cookie Authorization": "Autorizzazione Cookie",
  "Cookie Categories": "Categorie Cookie",
  "Copy Hash": "Copia Hash",
  "Core Message": "Messaggio Principale",
  "Cover Image": "Immagine di Copertina",
  "Cover Photo": "Foto di Copertina",
  "Create Account": "Crea Account"
}

update_translations('it', it_updates_1)
print("Updated IT Part 1")
