import json
import os

def update_translations(lang, updates):
    file_path = os.path.join(r"d:\Full-Projects\threadsV2\front\public\locales", lang, "translation.json")
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    data.update(updates)
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

it_updates_2 = {
  "Curate your best moments": "Cura i tuoi momenti migliori",
  "Current": "Attuale",
  "Current Points": "Punti attuali",
  "Daily": "Giornaliero",
  "Dark Mode": "Modalità Scura",
  "Data Interests": "Interessi sui Dati",
  "Data Policy": "Politica sui Dati",
  "Data Security": "Sicurezza dei Dati",
  "Data sharing is strictly governed by our privacy protocols and legal mandates.": "La condivisione dei dati è rigorosamente regolata dai nostri protocolli sulla privacy e dai mandati legali.",
  "Data Usage": "Utilizzo dei Dati",
  "Data We Collect": "Dati che Raccogliamo",
  "Delete Account": "Elimina Account",
  "Delete Highlight?": "Eliminare Highlight?",
  "Delete My Data": "Elimina i Miei Dati",
  "Delete Signal": "Elimina Segnale",
  "Deleting your account is permanent. All posts, media, connections and data will be liquidated from our servers instantly.": "L'eliminazione del tuo account è permanente. Tutti i post, i media, le connessioni e i dati saranno rimossi istantaneamente dai nostri server.",
  "Describe the system abnormality or inquiry details...": "Descrivi l'anomalia del sistema o i dettagli della richiesta...",
  "Direct Mail": "Posta Diretta",
  "Discover all creators": "Scopri tutti i creatori",
  "Discover Minds": "Scopri Menti",
  "Discover more circles": "Scopri più circoli",
  "Discover Network": "Scopri la Rete",
  "Discover trending content, connect with creators, and explore the global conversation.": "Scopri i contenuti di tendenza, connettiti con i creatori ed esplora la conversazione globale.",
  "Discovery": "Scoperta",
  "Discovery Active": "Scoperta Attiva",
  "Discovery Engine Active": "Motore di Scoperta Attivo",
  "Discussion": "Discussione",
  "Dive into the most engaging video content from across the network.": "Immergiti nei contenuti video più coinvolgenti di tutta la rete.",
  "Do Tasks": "Esegui Compiti",
  "Download a copy of your personal data archive for portability and local storage.": "Scarica una copia del tuo archivio dati personali per la portabilità e la conservazione locale.",
  "Drafts": "Bozze",
  "Earn XP for meaningful activity. Unlock advanced features and climb to Legend status.": "Guadagna XP per attività significative. Sblocca funzionalità avanzate e scala fino allo stato di Leggenda.",
  "Efficiency": "Efficienza",
  "Elite Verified": "Verificato Élite",
  "Email field is required": "Il campo email è obbligatorio",
  "Emergency Uplink": "Uplink di Emergenza",
  "Enable 2FA": "Abilita 2FA",
  "End of Signal Broadcast": "Fine della Trasmissione Segnale",
  "Engage with the community and unlock exclusive profile features.": "Interagisci con la community e sblocca funzionalità esclusive del profilo.",
  "Engagement Potential": "Potenziale di Interazione",
  "Ensure login locations match your activity": "Assicurati che i luoghi di accesso corrispondano alla tua attività",
  "Enter highlight name...": "Inserisci il nome dell'highlight...",
  "Error joining community.": "Errore durante l'adesione alla community.",
  "Establish Link": "Stabilisci Collegamento",
  "Event Added Successfully": "Evento Aggiunto con Successo",
  "Event Deleted Successfully": "Evento Eliminato con Successo",
  "Event Protocol": "Protocollo Evento",
  "Event Updated Successfully": "Evento Aggiornato con Successo",
  "Expand Grid": "Espandi Griglia",
  "Expand your network. Connect with creators, innovators, and friends across the platform.": "Espandi la tua rete. Connettiti con creatori, innovatori e amici in tutta la piattaforma.",
  "Expect a response in your primary inbox soon.": "Riceverai presto una risposta nella tua casella di posta principale.",
  "Explore All Network Nodes": "Esplora tutti i nodi della rete",
  "Exploring the digital horizon.": "Esplorando l'orizzonte digitale.",
  "Failed to approve join request.": "Impossibile approvare la richiesta di adesione.",
  "Failed to copy message.": "Impossibile copiare il messaggio.",
  "Failed to delete message locally.": "Impossibile eliminare il messaggio localmente.",
  "Failed to delete message.": "Impossibile eliminare il messaggio.",
  "Failed to delete Music.": "Impossibile eliminare la musica.",
  "Failed to delete reel.": "Impossibile eliminare il reel.",
  "Failed to delete story.": "Impossibile eliminare la storia.",
  "Failed to fetch music.": "Impossibile recuperare la musica.",
  "Failed to fetch reels.": "Impossibile recuperare i reel.",
  "Failed to like message.": "Impossibile mettere mi piace al messaggio.",
  "Failed to like music.": "Impossibile mettere mi piace alla musica.",
  "Failed to like reel.": "Impossibile mettere mi piace al reel.",
  "Failed to publish story. Please try again.": "Impossibile pubblicare la storia. Riprova.",
  "Failed to reject join request.": "Impossibile rifiutare la richiesta di adesione.",
  "Failed to send join request.": "Impossibile inviare la richiesta di adesione.",
  "Failed to send message.": "Impossibile inviare il messaggio.",
  "Failed to send reply": "Impossibile inviare la risposta",
  "Failed to send report.": "Impossibile inviare la segnalazione.",
  "Failed to share music.": "Impossibile condividere la musica.",
  "Failed to update community rules.": "Impossibile aggiornare le regole della community.",
  "Follow our official channels for peak hour updates.": "Segui i nostri canali ufficiali per gli aggiornamenti sulle ore di punta.",
  "Follow Sluchitt": "Segui Sluchitt",
  "Frequency Node": "Nodo di Frequenza",
  "Frequency Pulses": "Impulsi di Frequenza",
  "Frequency Queue": "Coda di Frequenza",
  "Frequency Subject": "Soggetto della Frequenza",
  "Frequently Asked Questions": "Domande Frequenti",
  "Functional": "Funzionale",
  "Gain trust with a verification badge and priority signal rankings across the network.": "Guadagna fiducia con un badge di verifica e classifiche di segnale prioritarie in tutta la rete.",
  "Games Coming Soon!": "Giochi in Arrivo!",
  "Gateway ID": "ID Gateway",
  "Get help with using our features and tools.": "Ottieni aiuto sull'utilizzo delle nostre funzionalità e strumenti.",
  "Global Network": "Rete Globale",
  "Global Pulse": "Pulsazione Globale",
  "Highlight Name": "Nome Highlight",
  "How can we synchronize your experience?": "Come possiamo sincronizzare la tua esperienza?",
  "How to Earn XP": "Come Guadagnare XP",
  "How We Use Them": "Come Li Usiamo",
  "How We Use Your Data": "Come Utilizziamo i Tuoi Dati",
  "Hub Guidelines": "Linee Guida dell'Hub",
  "I Understood": "Ho Capito",
  "Identity Avatar": "Avatar Identità",
  "Identity Parameters": "Parametri Identità",
  "Identity Verification": "Verifica Identità",
  "Image size should not exceed 10MB.": "La dimensione dell'immagine non deve superare i 10 MB.",
  "Include uppercase and lowercase letters": "Includi lettere maiuscole e minuscole",
  "Included Stories": "Storie Incluse",
  "Incoming Base": "Base in Arrivo",
  "Independent Node": "Nodo Indipendente",
  "Index Operational": "Indice Operativo",
  "Information Sharing": "Condivisione Informazioni",
  "Initialize a direct support protocol": "Inizializza un protocollo di supporto diretto",
  "Initialize New Node": "Inizializza Nuovo Nodo",
  "Initialize Node": "Inizializza Nodo",
  "Initialize Support": "Inizializza Supporto",
  "Initiate Event": "Inizia Evento",
  "Inner Peace": "Pace Interiore",
  "Integrity Rating": "Valutazione Integrità",
  "Intellectual Property": "Proprietà Intellettuale",
  "Interaction Profile": "Profilo Interazione",
  "Interest must be at least 2 characters long.": "L'interesse deve contenere almeno 2 caratteri.",
  "Invalid file selected.": "File selezionato non valido.",
  "Invitation Only": "Solo su Invito",
  "Join us securely": "Unisciti a noi in sicurezza",
  "Kick Member": "Espelli Membro",
  "Knowledge Sectors": "Settori di Conoscenza",
  "Language Settings": "Impostazioni Lingua",
  "Layout Density": "Densità Layout",
  "Learn how we keep our community safe.": "Scopri come manteniamo sicura la nostra community.",
  "Level Up System": "Sistema di Aumento Livello",
  "Link Node": "Collega Nodo",
  "Live Chat": "Chat dal Vivo",
  "Live Feed Capture": "Cattura Feed dal Vivo",
  "Live network status": "Stato della rete in tempo reale",
  "Live Preview": "Anteprima dal Vivo",
  "Load more replies": "Carica altre risposte",
  "Loading Admin Console": "Caricamento Console di Amministrazione",
  "Loading Reports...": "Caricamento Segnalazioni...",
  "Manage blocked and restricted accounts.": "Gestisci account bloccati e limitati.",
  "Manage Highlight": "Gestisci Highlight",
  "Manage user roles, statuses, and permissions": "Gestisci ruoli utente, stati e permessi",
  "Manage users you have muted or blocked notifications from.": "Gestisci gli utenti che hai silenziato o bloccato.",
  "Manage who can see your content and how you interact with others.": "Gestisci chi può vedere i tuoi contenuti e come interagisci con gli altri.",
  "Manage your communities and memberships": "Gestisci le tue community e iscrizioni",
  "Manage your privacy preferences anytime in Settings.": "Gestisci le tue preferenze sulla privacy in qualsiasi momento nelle Impostazioni.",
  "Mark All Read": "Segna Tutto come Letto",
  "Mark Read": "Segna come Letto",
  "Message Transmitted": "Messaggio Trasmesso",
  "Monitor Activity": "Monitora Attività",
  "Music uploaded successfully!": "Musica caricata con successo!",
  "Muted Accounts": "Account Silenziati",
  "My Circles": "I Miei Circoli",
  "Navigating the grid without a signal pulse.": "Navigazione nella griglia senza impulso di segnale.",
  "Need assistance? Find answers and connect with support.": "Hai bisogno di assistenza? Trova risposte e contatta il supporto.",
  "Network Links": "Link di Rete",
  "Network Resonance": "Risonanza di Rete",
  "Network Resonance Analysis for": "Analisi Risonanza di Rete per",
  "Network Signals": "Segnali di Rete",
  "Neural Identity Index": "Indice Identità Neurale",
  "Neural Networks Online": "Reti Neurali Online",
  "New Creators": "Nuovi Creatori",
  "New Transmission": "Nuova Trasmissione",
  "No bio available": "Nessuna biografia disponibile",
  "No blocked accounts": "Nessun account bloccato",
  "No categories": "Nessuna categoria",
  "No changes to update.": "Nessuna modifica da aggiornare.",
  "No circles joined.": "Nessun circolo raggiunto.",
  "No Communities": "Nessuna community",
  "No Connection Found": "Nessuna connessione trovata",
  "No description provided.": "Nessuna descrizione fornita.",
  "No Frequencies Detected": "Nessuna frequenza rilevata",
  "No Hate Speech or Bullying": "Nessun incitamento all'odio o bullismo",
  "No interests added yet.": "Nessun interesse aggiunto ancora.",
  "No IP info": "Nessuna info IP",
  "No matches found": "Nessuna corrispondenza trovata",
  "No matches found in the registry": "Nessuna corrispondenza trovata nel registro",
  "No matching questions found for your query or selected topic.": "Nessuna domanda corrispondente trovata per la tua ricerca o argomento selezionato.",
  "No minds found in this sector.": "Nessuna mente trovata in questo settore.",
  "No notifications found under this filter": "Nessuna notifica trovata con questo filtro",
  "No pending reports found": "Nessuna segnalazione in sospeso trovata",
  "No reason": "Nessun motivo",
  "No recent news available in this category.": "Nessuna notizia recente disponibile in questa categoria.",
  "No Repeat": "Nessuna Ripetizione",
  "No signals detected": "Nessun segnale rilevato",
  "No Signals Detected In This Cycle": "Nessun segnale rilevato in questo ciclo",
  "No signals found": "Nessun segnale trovato",
  "No signals found in this sector": "Nessun segnale trovato in questo settore",
  "No signals on the radar": "Nessun segnale sul radar",
  "No stories available": "Nessuna storia disponibile",
  "No suggestions for now": "Nessun suggerimento per ora",
  "No supplementary data available.": "Nessun dato supplementare disponibile.",
  "No trending hashtags right now.": "Nessun hashtag di tendenza al momento.",
  "No trends found yet.": "Nessuna tendenza trovata ancora.",
  "No users found": "Nessun utente trovato",
  "No views yet": "Nessuna visualizzazione ancora",
  "No Visuals Found": "Nessun contenuto visivo trovato",
  "Node Initialized": "Nodo Inizializzato"
}

update_translations('it', it_updates_2)
print("Updated IT Part 2")
